server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
upload:
  directory: static/images
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url : jdbc:h2:tcp://localhost/~/one-grain-daily
#    username: sa
#    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hackathon?serverTimezone=Asia/Seoul
    username: cho
    password: hee6455
#    url : jdbc:mysql://115.85.183.243:3306/hackathon?serverTimezone=Asia/Seoul
#    username: spring
#    password: hee6455
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
